[package.build.backend]
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]
name = "pixi-build-ros"
version = "*"

[package.build.config]
extra-input-globs = [
    "**/*.py",
]

[package.host-dependencies]
ros2-distro-mutex = ">=0.12,<0.13"

[package.build-dependencies]
ros2-distro-mutex = ">=0.12,<0.13"

[package.run-dependencies]
ros2-distro-mutex = ">=0.12,<0.13"